version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: flashcard-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/flashcard_db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: flashcard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:

